### ISSUE TITLE
Convert tests to use docker library

### ISSUE THREAD

**Issue by felddy** [cisagov/skeleton-docker#155]
# 💡 Summary #

Remove the use of `dockerc` from the tests.  Implement using the official `docker` library.

## Motivation and context ##

`dockerc` is deprecated.  

## Implementation notes ##

Take a look at this project for an example of how to make these changes.

- https://github.com/felddy/foundryvtt-docker/blob/develop/tests/conftest.py

Specifically this jazz:

https://github.com/felddy/foundryvtt-docker/blob/a3e25d7675ff7841d7ba0051c1880d169f41b3f9/tests/conftest.py#L42-L63

## Acceptance criteria ##

How do we know when this work is done?

- [ ] `dockerc` is no longer used
- [ ] `docker` library is used

**Comment by nbienkowska** [comment]
Hi, can I take this issue?

**Comment by felddy** [comment]
@nbienkowska, Absolutely!  Thank you for offering. 

We've got a pretty comprehensive review process and can be quite pedantic.  So take a look at the `CONTRIBUTING` file and possibly our [development guide](https://github.com/cisagov/development-guide).  

If you have any questions feel free to reach out to any of the team @cisagov/team-ois 

Thank you again!

**Comment by lfilip-ivaal** [comment]
Picking this issue up to investigate.

**Comment by jsf9k** [comment]
@lfilip-ivaal - This issue was resolved via pull request #167 and should have been closed when that PR was merged.  There is nothing to be done here.
