### ISSUE TITLE
Split version check test into three separate tests

### ISSUE THREAD

**Issue by felddy** [cisagov/skeleton-docker#5]
This test should be split into three separate tests (one for each assertion):
- [x] stdout matches version stored in project
- [x] container label matches version stored in project
- [x] `TRAVIS_TAG` matches version stored in project See: [`skeleton-python-library`](https://github.com/cisagov/skeleton-python-library/blob/a9e5f7afefd9693b306324ac4c0712d1f79ef344/tests/test_example.py#L46-L53)

https://github.com/cisagov/skeleton-docker/blob/fb5b9911c5ae2af24ff187b80ca113b109363a1e/tests/container_test.py#L37-L55

**Comment by mcdonnnj** [comment]
This appears to have been resolved in #9 so I am closing the issue.
