### ISSUE TITLE
Add better documentation for cross building container from source.

### ISSUE THREAD

**Issue by felddy** [cisagov/skeleton-docker#50]
# 💡 Summary #

Add better build docs.

## Motivation and context ##

I've already written them.  Backport!

This would be useful because...

## Implementation notes ##

See: https://github.com/felddy/foundryvtt-docker#building-from-source

**Comment by mcdonnnj** [comment]
I was able to use the directions you wrote to debug cross-platform builds on my local machine for [cisagov/vdp-scanner-docker](https://github.com/cisagov/vdp-scanner-docker) after our conversation yesterday. Definitely looking forward to these being baked into the repositories in the future.
