### ISSUE TITLE
Switch "docker-compose" to "docker compose". 

### ISSUE THREAD

**Issue by felddy** [cisagov/skeleton-docker#54]
# 💡 Summary #

The `docker` command is now capable of doing the work of `docker-compose`.    This message is now emitted by `docker-compose`:

```console
❱ docker-compose up
Docker Compose is now in the Docker CLI, try `docker compose up`
```

## Motivation and context ##

Eventually this will be the way™. 

## Implementation notes ##

https://docs.docker.com/compose/cli-command/

I've noticed that the new command is more pedantic about the `docker-compose.yml` files. 
Specifically, it does not permit quoted integers for port numbers.

## Acceptance criteria ##

How do we know when this work is done?

- [ ] all `docker-compose` references converted to `docker compose`
- [ ] all included `docker-compose.yml` files work with new command

**Comment by Chealer** [comment]
Greetings,
I have no clue what skeleton-docker is, but having stumbled on this ticket, I would advise you to have a look at [the ticket about compose-cli's new message](https://github.com/docker/compose-cli/issues/1149), which indicates that `docker compose up` in currently in preview, before proceeding with this.

**Comment by mcdonnnj** [comment]
This appears to have been done in https://github.com/cisagov/skeleton-docker/pull/105.
